#!/bin/sh

symbol() {
  if nmcli g status | grep -q 'connected'; then echo "󰤨"; else echo "󰤭"; fi
}

name() {
  nmcli | grep "^wlp" | sed 's/\ connected\ to\ /Connected to /g' | cut -d ':' -f2
}

[ "$1" = "icon" ] && symbol && exit
[ "$1" = "name" ] && name && exit
